#! /bin/sh

sxhkd &
xfce4-power-manager &
picom --config $HOME/.config/picom/picom.conf &
wal -a "0.7" -i $HOME/Pictures/wallpaper/wp5748138-minimalist-black-and-white-wallpapers.png
$HOME/.config/polybar/launch.sh &
$HOME/.config/polybar/scripts/spotify/launchlistener.sh &
bspc monitor -d 1 2 3 4 5 6 7

bspc config border_width 3
bspc config window_gap 10
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focused_border_color \#A89984;
bspc config normal_border_color \#282828;

bspc rule -a Screenkey manage=off
